---
- name: Use Ansible (in AAP) to Run a Terraform Project
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: import deploy_ec2 role
    ansible.builtin.import_role:
      name: deploy_ec2
